name: Deploy CoPilot branch to gh-pages (CoPilot)

on:
  push:
    branches: [ "CoPilot" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CoPilot
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional build step if you have a build process:
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      # - name: Build site
      #   run: |
      #     npm ci
      #     npm run build

      - name: Deploy to gh-pages branch under /CoPilot
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .                # change if you build into ./dist or similar
          destination_dir: CoPilot
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
